### ISSUE TITLE
could not load plugin assembly for type Cheesebaron.MvxPlugins.Settings.PluginLoader

### ISSUE THREAD

**Issue by edikep2000** [Cheesebaron/Cheesebaron.MvxPlugins#62]
Please I am having the following problem Running my MVVMCross Application on a Windows Phone 8 Device

My Package Config is:

    <?xml version="1.0" encoding="utf-8"?>
    <packages>
      <package id="Bulboss.MvvmCross.Plugins.UserInteraction" version="1.3.1" targetFramework="wp8" />
      <package id="Cheesebaron.MvxPlugins.Settings" version="2.1.0" targetFramework="wp8" />
      <package id="Microsoft.Bcl" version="1.1.9" targetFramework="wp8" />
      <package id="Microsoft.Bcl.Build" version="1.0.14" targetFramework="wp8" />
      <package id="Microsoft.Net.Http" version="2.2.22" targetFramework="wp8" />
      <package id="MvvmCross" version="4.3.0" targetFramework="wp8" />
      <package id="MvvmCross.Binding" version="4.3.0" targetFramework="wp8" />
      <package id="MvvmCross.Core" version="4.3.0" targetFramework="wp8" />
      <package id="MvvmCross.Platform" version="4.3.0" targetFramework="wp8" />
      <package id="MvvmCross.Plugin.File" version="4.3.0" targetFramework="wp8" />
      <package id="MvvmCross.Plugin.Json" version="4.3.0" targetFramework="wp8" />
      <package id="MvvmCross.Plugin.Location" version="4.3.0" targetFramework="wp8" />
      <package id="MvvmCross.Plugin.Messenger" version="4.3.0" targetFramework="wp8" />
      <package id="MvvmCross.Plugin.Network" version="4.3.0" targetFramework="wp8" />
      <package id="MvvmCross.Plugin.Visibility" version="4.3.0" targetFramework="wp8" />
      <package id="MvvmCross.StarterPack" version="4.3.0" targetFramework="wp8" />
      <package id="Newtonsoft.Json" version="9.0.1" targetFramework="wp8" />
      <package id="WPtoolkit" version="4.2013.08.16" targetFramework="wp8" />
    </packages>

I have the plugin bootstrapped as follows

     public class SettingsPluginBootstrap : MvxPluginBootstrapAction<Cheesebaron.MvxPlugins.Settings.PluginLoader>
        {
    
        }

And I use the Settings Plugin like so
 

    public class SettingsService
        {
    
            private ISettings _settings;
    
            public SettingsService(ISettings settingsService)
            {
                _settings = settingsService;
            }
    }

My windows Phone Application Constructor Is Setup as follows

     public App()
            {
                var setup = new Setup(RootFrame);
                setup.Initialize();
            }

But whenever setup.Initialize() is called. I get the followin exception

    Additional information: could not load plugin assembly for type Cheesebaron.MvxPlugins.Settings.PluginLoader
       at MvvmCross.Platform.Plugins.MvxFilePluginManager.LoadAssembly(Type toLoad)
       at MvvmCross.Platform.Plugins.MvxFilePluginManager.FindPlugin(Type toLoad)
       at MvvmCross.Platform.Plugins.MvxPluginManager.ExceptionWrappedLoadPlugin(Type toLoad)
       at MvvmCross.Platform.Plugins.MvxPluginManager.EnsurePlatformAdaptionLoaded[T]()
       at Cheesebaron.MvxPlugins.Settings.PluginLoader.EnsureLoaded()
       at MvvmCross.Platform.Plugins.MvxPluginManager.EnsurePluginLoaded(IMvxPluginLoader pluginLoader)
       at MvvmCross.Platform.Plugins.MvxPluginManager.EnsurePluginLoaded(Type type)
       at MvvmCross.Platform.Plugins.MvxPluginManager.EnsurePluginLoaded[TType]()
       at MvvmCross.Platform.Plugins.MvxPluginBootstrapAction`1.Load(IMvxPluginManager manager)
       at MvvmCross.Platform.Plugins.MvxPluginBootstrapAction`1.RunAction()
       at System.Action.Invoke()
       at MvvmCross.Platform.IoC.MvxSimpleIoCContainer.InternalSetResolver(Type tInterface, IResolver resolver)
       at MvvmCross.Platform.IoC.MvxSimpleIoCContainer.RegisterSingleton[TInterface](TInterface theObject)
       at MvvmCross.Platform.Mvx.RegisterSingleton[TInterface](TInterface service)
       at MvvmCross.Core.Platform.MvxSetup.InitializePluginFramework()
       at MvvmCross.Core.Platform.MvxSetup.InitializeSecondary()
       at MvvmCross.Core.Platform.MvxSetup.Initialize()
       at IGovern.WinPhone.App..ctor()

Please What Am I Doing Wrong???

**Comment by Cheesebaron** [comment]
What assemblies are referenced in your Windows Phone project?

**Comment by edikep2000** [comment]
![image](https://cloud.githubusercontent.com/assets/2823934/20262216/90c95b4c-aa61-11e6-9d1b-13275b5e05db.png)

**Comment by Cheesebaron** [comment]
So if you look closely. There is only Cheesebaron.MvxPlugins.Settings. No platform specific dll was added.

Looking in: https://github.com/Cheesebaron/Cheesebaron.MvxPlugins/tree/master/Settings There is no WindowsPhone project and only WindowsCommon.

This means that Cheesebaron.MvxPlugins.Settings is Windows Phone 8.1 non-Silverlight and up. 

So, sorry, there is no support for Windows Phone 8, no plans to support it either. I recommend you upgrading to Windows Phone 8.1 non-Silverlight.

**Comment by Cheesebaron** [comment]
I've added an overview of support platforms in the README.md
